CREATE DATABASE IF NOT EXISTS tienda;

USE tienda;

CREATE TABLE IF NOT EXISTS users(
  id INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id),
  username VARCHAR(16) NOT NULL,
  password VARCHAR(60) NOT NULL,
);

CREATE TABLE IF NOT EXISTS products(
  id INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id),
  name VARCHAR(60) NOT NULL,
  description VARCHAR(255) NOT NULL,
  price DECIMAL(5,2) NOT NULL,
)

CREATE TABLE IF NOT EXISTS orders(
  id INT(11) NOT NULL AUTO_INCREMENT, PRIMARY KEY(id),
  user_id INT(11) NOT NULL,
  product_id INT(11) NOT NULL,
  quantity INT(11) NOT NULL,
)
